"""
Django settings for WaiverWire project.

Generated by 'django-admin startproject' using Django 3.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-i1l(e27&kdv$v4nv1klv7_terx$ry4#i*rm*_h+tu&r=#7vffy'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['localhost', '18.118.247.28', 'waiverwire.org', '172.31.21.12', '3.132.115.70', '3.16.58.218']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'da_wire',
    'django.contrib.humanize',
]

# Stripe test values
#STRIPE_PUBLISHABLE_KEY = 'pk_test_51Jsg0jHSiSQekQU9CAieigKDsNswQkm9R6rIYdrSx2AQVlQ9XUByJQhsCOTblp5WvlOwFkLRtOXCVd2znlhByFkr00I3eMU8Wy'
#STRIPE_SECRET_KEY = 'sk_test_51Jsg0jHSiSQekQU9v2yX6MBq4VudhJO52pI40xLRfLNp1aDNl7DS8RgBc0ILZgxVm9pwEVxb7BUXshZkpTDPP1Nr00rwssKPAy'
#STRIPE_ENDPOINT_SECRET = 'whsec_K4LozEU04yBGPrXf1PTl06hQ0nDiLTbx'
# Stripe production values
STRIPE_PUBLISHABLE_KEY = 'pk_live_51Jsg0jHSiSQekQU9A9JIv86sI263UKzSed9Ku2M1DNW5V3QVbW2XfBMKAE0r6ePhnkIqgGA9OOoIAKIGgqbCyzKk00FRvGr0YQ'
STRIPE_SECRET_KEY = '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'
STRIPE_ENDPOINT_SECRET = 'whsec_IEa3ybCuiSK5IIkIMybYn42YcQciKuHu'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'WaiverWire.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'WaiverWire.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'djongo',
        'NAME': 'waiverwire',
        'ENFORCE_SCHEMA': False,
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'
if DEBUG:
    STATICFILES_DIRS = ["C:\\Users\\15134\\Desktop\\WaiverWire\\WaiverWire\\static"]
else:
    import os
    STATIC_ROOT = os.path.join(BASE_DIR, "WaiverWire/static/")

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
