# Generated by Django 3.2.6 on 2021-08-13 19:04

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('pkey', models.IntegerField(primary_key=True, serialize=False)),
                ('color', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('text', models.TextField(validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(2000)])),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='MLBAffiliate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('logo', models.CharField(default='', max_length=20)),
                ('colors', models.ManyToManyField(to='da_wire.Color')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='da_wire.level')),
            ],
        ),
        migrations.CreateModel(
            name='MLBTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('middle_initial', models.CharField(blank=True, default='', max_length=2)),
                ('number', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)])),
                ('is_FA', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('bb_ref', models.CharField(default='', max_length=300)),
                ('mlbaffiliate', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='da_wire.mlbaffiliate')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('players', models.ManyToManyField(to='da_wire.Player')),
                ('team_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_trade_team_from', to='da_wire.mlbaffiliate')),
                ('team_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_trade_team_to', to='da_wire.mlbaffiliate')),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('years', models.IntegerField(default=1)),
                ('money', models.IntegerField(default=30000)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('tid', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_up', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='da_wire.transaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('players', models.ManyToManyField(to='da_wire.PlayerTrade')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='da_wire.transaction')),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='da_wire.position'),
        ),
        migrations.AddField(
            model_name='player',
            name='salary',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='da_wire.salary'),
        ),
        migrations.AddField(
            model_name='player',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='da_wire.transaction'),
        ),
        migrations.CreateModel(
            name='PersonalLeave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('length', models.IntegerField(default=10)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='da_wire.player')),
                ('team_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='da_wire.mlbaffiliate')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='da_wire.transaction')),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('is_rehab_assignment', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('from_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option_from_level', to='da_wire.level')),
                ('mlbteam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='da_wire.mlbteam')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='da_wire.player')),
                ('to_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option_to_level', to='da_wire.level')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='da_wire.transaction')),
            ],
        ),
        migrations.AddField(
            model_name='mlbaffiliate',
            name='mlbteam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='da_wire.mlbteam'),
        ),
        migrations.CreateModel(
            name='InjuredList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('length', models.IntegerField(default=10)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='da_wire.player')),
                ('team_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='da_wire.mlbaffiliate')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='da_wire.transaction')),
            ],
        ),
        migrations.CreateModel(
            name='FASignings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('is_draftpick', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='da_wire.player')),
                ('team_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='da_wire.mlbaffiliate')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='da_wire.transaction')),
            ],
        ),
        migrations.CreateModel(
            name='DFA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='da_wire.player')),
                ('team_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='da_wire.mlbaffiliate')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='da_wire.transaction')),
            ],
        ),
        migrations.CreateModel(
            name='CommentVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_up', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='da_wire.comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='transaction',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='da_wire.transaction'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='CallUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('from_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='callup_from_level', to='da_wire.level')),
                ('mlbteam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='da_wire.mlbteam')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='da_wire.player')),
                ('to_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='callup_to_level', to='da_wire.level')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='da_wire.transaction')),
            ],
        ),
        migrations.AddConstraint(
            model_name='transactionvote',
            constraint=models.UniqueConstraint(fields=('user', 'transaction'), name='unique_user_transaction'),
        ),
        migrations.AddConstraint(
            model_name='commentvote',
            constraint=models.UniqueConstraint(fields=('user', 'comment'), name='unique_user_comment'),
        ),
    ]
