# Generated by Django 3.2.6 on 2021-10-08 03:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('da_wire', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerTradeProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('players', models.ManyToManyField(to='da_wire.Player')),
                ('team_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_trade_proposal_team_from', to='da_wire.mlbaffiliate')),
                ('team_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_trade_proposal_team_to', to='da_wire.mlbaffiliate')),
            ],
        ),
        migrations.CreateModel(
            name='TradeProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('players', models.ManyToManyField(to='da_wire.PlayerTradeProposal')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='da_wire.transaction')),
            ],
        ),
    ]
