# Generated by Django 3.2.5 on 2021-08-01 23:36

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('da_wire', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fasignings',
            name='is_draftpick',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
        migrations.CreateModel(
            name='CallUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('from_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='da_wire.level')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='da_wire.player')),
            ],
        ),
    ]
