# Generated by Django 3.2.6 on 2021-08-18 14:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('da_wire', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mlbteam',
            name='is_NL',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
    ]
