# Generated by Django 3.2.6 on 2021-10-08 09:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('da_wire', '0002_playertradeproposal_tradeproposal'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='value',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AddField(
            model_name='tradeproposal',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
