# Generated by Django 3.2.6 on 2021-08-23 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('da_wire', '0002_mlbteam_is_nl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mlbaffiliate',
            name='colors',
            field=models.ManyToManyField(blank=True, to='da_wire.Color'),
        ),
    ]
