# Generated by Django 3.2.5 on 2021-08-02 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('da_wire', '0002_auto_20210801_1936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playertrade',
            name='player',
        ),
        migrations.AddField(
            model_name='playertrade',
            name='players',
            field=models.ManyToManyField(to='da_wire.Player'),
        ),
    ]
