# Generated by Django 3.2.5 on 2021-08-07 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('da_wire', '0004_auto_20210807_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='transaction',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='da_wire.transaction'),
        ),
    ]
