# Generated by Django 3.2.6 on 2021-08-24 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('da_wire', '0004_alter_color_pkey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='pkey',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
