# Generated by Django 3.2.5 on 2021-08-08 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('da_wire', '0005_comment_transaction'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='commentvote',
            constraint=models.UniqueConstraint(fields=('user', 'comment'), name='unique_user_comment'),
        ),
        migrations.AddConstraint(
            model_name='transactionvote',
            constraint=models.UniqueConstraint(fields=('user', 'transaction'), name='unique_user_transaction'),
        ),
    ]
