# Generated by Django 3.2.6 on 2021-10-27 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('da_wire', '0007_player_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='picture',
            field=models.CharField(blank=True, default=None, max_length=1000),
        ),
    ]
