# Generated by Django 3.2.6 on 2021-10-28 23:52

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('da_wire', '0008_alter_player_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatterStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avg', models.DecimalField(decimal_places=3, max_digits=3)),
                ('OBP', models.DecimalField(decimal_places=3, max_digits=3)),
                ('OPS', models.DecimalField(decimal_places=3, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='PitcherStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ERA', models.DecimalField(decimal_places=2, max_digits=6)),
                ('SO', models.IntegerField()),
                ('WHIP', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_mlb', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('batter_stats', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='da_wire.batterstats')),
                ('pitcher_stats', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='da_wire.pitcherstats')),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='stats',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='da_wire.stats'),
        ),
    ]
