# Generated by Django 3.2.6 on 2021-10-29 00:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('da_wire', '0011_alter_player_stats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stats',
            name='batter_stats',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='da_wire.batterstats'),
        ),
        migrations.AlterField(
            model_name='stats',
            name='pitcher_stats',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='da_wire.pitcherstats'),
        ),
    ]
