# Generated by Django 3.2.9 on 2021-11-08 04:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('da_wire', '0014_auto_20211029_0422'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaiverClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='da_wire.player')),
                ('team_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waiver_claim_team_from', to='da_wire.mlbaffiliate')),
                ('team_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waiver_claim_team_to', to='da_wire.mlbaffiliate')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='da_wire.transaction')),
            ],
        ),
    ]
