# Generated by Django 3.2.9 on 2021-11-15 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('da_wire', '0017_comment_reply_to'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReplyNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='da_wire.comment')),
            ],
        ),
    ]
